---
- name: Install mariadb
  hosts: all
  become: yes
  become_method: sudo
  tasks:
     - name: 1. Install MariaDB server package
       apt: name=mariadb-server state=present

     - name: 2. Start Mysql Service
       service: name=mysql state=started enabled=true
