---
     - name: install JDK 11
       apt:
         name: openjdk-11-jdk
         state: present
        
     - name: Download apache tomcat installer
       shell: wget --user=admin --password=admin123 http://13.52.130.201:8081/repository/test/apache-tomcat-9.0.21.tar.gz -O /home/apache-tomcat-9.0.21.tar.gz
       
     - name: add tomcat group
       group:
          name: tomcat

     - name: add tomcat user
       user:
          name: tomcat
          group: tomcat
          home: /user/share/tomcat
          createhome: no

     - name: create /opt/tomcat directory
       file:
         path: /opt/tomcat
         state: directory
         mode: 0755

     - name: download & unarchive
       unarchive:
           src: /home/apache-tomcat-9.0.21.tar.gz
           dest: /opt/tomcat
           remote_src: yes
           extra_opts: [--strip-components=1]
           
     - name: Change ownership
       file:
          path: /opt/tomcat
          owner: tomcat
          group: tomcat
          mode: "u+rwx,g+rx,o=rx"
          recurse: yes
          state: directory
          
     - name: Copy Tomcat service from local to remote
       copy:
         src: tomcat.service
         dest: /etc/systemd/system/
         mode: 0755

     - name: Start and enable Tomcat service
       systemd:
          name: tomcat
          state: started
          enabled: true
          daemon_reload: true
